title: Ao.NET

# description: ...

url: "https://tinko26.github.io"

baseurl: "/ao.net"

permalink: pretty

search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

heading_anchors: true

remote_theme: just-the-docs/just-the-docs

color_scheme: ao

plugins:
  - jekyll-seo-tag

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2022 Stefan Wagner.<br/>Distributed by an <a href=\"https://github.com/tinko26/ao.net/tree/main/LICENSE\">MIT license</a>.<br/><br/><a href=\"https://github.com/tinko26/ao.net\">Ao.NET on GitHub</a>"

last_edit_timestamp: false
last_edit_time_format: "%b %e %Y at %I:%M %p"

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

