title: Ao.NET

# description: ...

url: "https://tinko26.github.io"

baseurl: "/ao.net"

permalink: pretty

search_enabled: false

heading_anchors: true

remote_theme: just-the-docs/just-the-docs

color_scheme: ao

plugins:
  - jekyll-seo-tag

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2022 Stefan Wagner.<br/>Distributed by an <a href=\"https://github.com/tinko26/ao.net/tree/main/LICENSE\">MIT license</a>.<br/><br/><a href=\"https://github.com/tinko26/ao.net\">Ao.NET on GitHub</a>"

last_edit_timestamp: false
last_edit_time_format: "%b %e %Y at %I:%M %p"

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

